"""обновил модели записей, роскоментировал поле, связь пользователя и заметки

Revision ID: 7e7ac79cf9c8
Revises: ff700fb09fa7
Create Date: 2024-12-24 12:28:45.946935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7ac79cf9c8'
down_revision: Union[str, None] = 'ff700fb09fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'users_id')
    # ### end Alembic commands ###
