"""degrade table contacts

Revision ID: 925e491cb6dc
Revises: 56fb3e56038f
Create Date: 2024-12-22 22:28:51.124487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925e491cb6dc'
down_revision: Union[str, None] = '56fb3e56038f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_users_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'users_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_users_id_fkey', 'contacts', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
